// <auto-generated />
namespace BookRentalService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingGenres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingGenres));
        
        string IMigrationMetadata.Id
        {
            get { return "202001310950025_AddingGenres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
